<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit542e8ed0d2099d01ec863a1f9165e824
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
        'D' => 
        array (
            'Dotenv\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
        'Dotenv\\' => 
        array (
            0 => __DIR__ . '/..' . '/vlucas/phpdotenv/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit542e8ed0d2099d01ec863a1f9165e824::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit542e8ed0d2099d01ec863a1f9165e824::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
